spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/draftly_ai
    username: kredx
    password: kredx@2024

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 975004853781-atm3uv8nek7t689nlfnnr1s53t3d7qm0.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post

            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/gmail.modify
              - https://www.googleapis.com/auth/gmail.send

        provider:
          google:
            issuer-uri: https://accounts.google.com

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.flywaydb: DEBUG
    org.flywaydb.core.internal.scanner: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.http.client: DEBUG

openai:
  api-key: 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

gemini:
  api-key: AIzaSyA2qix_MBpfmza9UdVStxoeNHtIU6bOl34